name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to a server
        run: java -jar /home/ubuntu/spring-petclinic.jar
          ssh ubuntu@ec2-18-233-151-52 "/home/ubuntu && ./deploy.sh"
