name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to a server
        run: |
          scp target/spring-petclinic.jar ubuntu@54.159.151.232:/home/ubuntu/spring-petclinic.jar
          ssh ubuntu@54.159.151.232 "cd /home/ubuntu && ./deploy.sh"


