name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to a server
        uses: appleboy/ssh-action@master
        with:
          host: 54.159.151.232
          username: ubuntu
          key: private
          script: |
            cd /home/ubuntu
            ./deploy.sh
